from selenium.webdriver.common.by import By

class AuthLocators:
    AUTH_EMAIL = (By.ID,'username')
    AUTH_PASS = (By.ID,'password')
    AUTH_BTN = (By.ID,'kc-login')
    AUTH_PHONE = (By.ID,'username')
    AUTH_LOGIN = (By.ID,'username')
    AUTH_ACCOUNT = (By.ID,'username')
    AUTH_ERROR_MESSAGE = (By.ID, 'form-error-message')
    REGISTER = (By.ID, 'kc-register')
    REG_BTN = (By.CLASS_NAME, 'rt-btn')
    REG_ERROR_MESSAGE = (By.CSS_SELECTOR, '.rt-input-container__meta--error')
    PASS_RECOVERY = (By.ID, 'forgot_password')
    RECOVERY_TITLE = (By.CSS_SELECTOR, '.card-container__title')
    AGREEMENT = (By.LINK_TEXT, 'пользовательского соглашения')
    AGREEMENT_TITLE = (By.CLASS_NAME, 'offer-title')
    INPUT_FIRSTNAME = (By.CSS_SELECTOR, 'input[name="firstName"]')
    INPUT_LASTNAME = (By.CSS_SELECTOR, 'input[name="lastName"]')
    TEMPORARY_CODE_BTN = (By.ID, 'back_to_otp_btn')
    TEMPORARY_CODE_TITLE = (By.CSS_SELECTOR, '.card-container__title')
    INPUT_ADDRESS = (By.ID, 'address')
    INPUT_PASSWORD = (By.ID, 'password')
    INPUT_CONFIRM_PASS = (By.ID, 'password-confirm')
    REG_TEXT_ERROR = (By.CLASS_NAME, 'card-modal__title')
